"""The full check catalogue, corpus/09 section 2.

Eight classes: Completeness, Validity, Uniqueness, Consistency,
Reconciliation, Continuity, Anomaly, Freshness. Severity is enforced in
code, not left to judgement at runtime -- BLOCKING halts statement assembly
or the pack, WARNING badges the number and lets it through, INFORMATIONAL
appears only in the exception queue.

exception.exception_class uses corpus/09's own eight class names
(completeness, validity, uniqueness, consistency, reconciliation,
continuity, anomaly, freshness) rather than corpus/04's inline DDL comment
list, which names 'unmapped' as a top-level class instead of 'freshness'.
corpus/09 is the check catalogue's own authority (its title is literally
"Data Quality and Reconciliation"); corpus/04's comment is a supporting
table definition, and the column itself is untyped text with no CHECK
constraint. 'Unmapped' is filed under completeness here (corpus/09 section
2.1's own row: "An account carries value but has no mapping").

**Scope boundary, stated plainly.** Only COA, TB, GL and Bank have an
ingestion pipeline (Sprint 1 + this sprint's Bank addition) -- Sales
Register, Purchase Register, AR/AP Ageing, Inventory, MFG Production and
Consumer Sales are generated by the synthetic dataset but nothing stages or
canonically writes them. Five of the thirteen seeded defects (corpus/11
section 2.2, #7 dual UOM, #8 credit note no reason, #9 margin sign flip, #11
#DIV/0!, #12 zero-COGS consumer) land in those un-ingested streams and are
structurally undetectable by any check built here -- not a gap in this
module's logic, a gap in which streams have been ingested at all. The
eight checks below cover exactly the defects that touch an ingested stream:
#1 backdated batch, #2 duplicate content, #3 stream not supplied, #4 TB
imbalance, #5 new ledger mid-year, #6 schema hash change (blocks the load
itself, Sprint 1 -- surfaced here as a completeness signal, not re-detected),
#10 unclassifiable ledgers (suspense.unmapped), #13 absorption variance
(a judgement class, never auto-accepted -- src/mapping/engine.py).

Split into DB-fetching check functions (each returns a list of
ExceptionCandidate) and pure helpers, continuing the pattern used
throughout src/quality/.
"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import date, datetime, timezone
from decimal import Decimal

# D-053's resolved text (corpus/00 section 2b): "Block above 2% of period
# value, badge between 0.5% and 2%, silent below 0.5%."
UNMAPPED_BLOCK_THRESHOLD_PCT = Decimal("0.02")
UNMAPPED_WARN_THRESHOLD_PCT = Decimal("0.005")


@dataclass
class ExceptionCandidate:
    exception_class: str
    severity: str  # 'blocking' | 'warning' | 'informational'
    description: str
    period_key: str | None = None
    object_type: str | None = None
    object_ref: str | None = None
    value_inr: Decimal | None = None
    suggested_action: str | None = None


def write_exceptions(conn, schema: str, tenant_id: str, entity_id: int,
                        candidates: list[ExceptionCandidate], load_run_id: int | None = None) -> list[int]:
    ids = []
    with conn.cursor() as cur:
        for c in candidates:
            cur.execute(
                f'INSERT INTO "{schema}".exception '
                f'(tenant_id, entity_id, exception_class, severity, period_key, object_type, object_ref, '
                f' value_inr, description, suggested_action, load_run_id) '
                f'VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) RETURNING exception_id',
                (tenant_id, entity_id, c.exception_class, c.severity, c.period_key, c.object_type, c.object_ref,
                 c.value_inr, c.description, c.suggested_action, load_run_id),
            )
            ids.append(cur.fetchone()[0])
    return ids


# --------------------------------------------------------------- Completeness

def check_zero_gl_rows(conn, schema: str, tenant_id: str, entity_id: int, period_key: str) -> list[ExceptionCandidate]:
    """corpus/09 section 2.1: 'A month in the requested range has zero GL
    rows' -- BLOCKING, period not reportable."""
    with conn.cursor() as cur:
        cur.execute(
            f'SELECT count(*) FROM "{schema}".fact_gl_entry '
            f'WHERE tenant_id = %s AND entity_id = %s AND period_key = %s AND is_current',
            (tenant_id, entity_id, period_key),
        )
        count = cur.fetchone()[0]
    if count > 0:
        return []
    return [ExceptionCandidate(
        "completeness", "blocking", f"No GL rows at all for {period_key} -- the period is not reportable.",
        period_key=period_key, object_type="period", object_ref=period_key,
        suggested_action="Upload the GL export for this period.",
    )]


def check_stream_supplied(conn, schema: str, tenant_id: str, entity_id: int, period_key: str,
                             stream: str) -> list[ExceptionCandidate]:
    """corpus/09 section 2.1: 'A required stream has not been supplied at
    all' -- BLOCKING. stream: 'bank' (fact_bank_txn) or 'gl' (fact_gl_entry).
    Detected from whether the canonical fact table has any row for the
    period, not from source_file (which does not carry a period column --
    a real Tally/bank export's date range is only known once its rows are
    staged)."""
    table = {"gl": "fact_gl_entry", "bank": "fact_bank_txn"}[stream]
    with conn.cursor() as cur:
        cur.execute(
            f'SELECT count(*) FROM "{schema}".{table} '
            f'WHERE tenant_id = %s AND entity_id = %s AND period_key = %s AND is_current',
            (tenant_id, entity_id, period_key),
        )
        count = cur.fetchone()[0]
    if count > 0:
        return []
    return [ExceptionCandidate(
        "completeness", "blocking", f"The {stream.upper()} stream has not been supplied at all for {period_key}.",
        period_key=period_key, object_type="period", object_ref=period_key,
        suggested_action=f"Upload the {stream.upper()} file for this period.",
    )]


def check_unmapped_value(conn, schema: str, tenant_id: str, entity_id: int, mapping_version_id: int,
                            period_key: str) -> list[ExceptionCandidate]:
    """corpus/09 section 2.1 + D-053: unmapped value below 0.5% is silent,
    0.5-2% is a WARNING, above 2% is BLOCKING."""
    with conn.cursor() as cur:
        cur.execute(
            f'SELECT COALESCE(SUM(period_value_inr), 0), '
            f"       COALESCE(SUM(period_value_inr) FILTER (WHERE canonical_class = 'suspense.unmapped'), 0) "
            f'FROM "{schema}".map_account WHERE mapping_version_id = %s',
            (mapping_version_id,),
        )
        total, unmapped = cur.fetchone()
    if total == 0:
        return []
    pct = unmapped / total
    if pct > UNMAPPED_BLOCK_THRESHOLD_PCT:
        severity = "blocking"
    elif pct > UNMAPPED_WARN_THRESHOLD_PCT:
        severity = "warning"
    else:
        return []
    return [ExceptionCandidate(
        "completeness", severity,
        f"Unmapped value is {pct:.2%} of period value (Rs {unmapped:,.0f}) -- above the D-053 "
        f"{'blocking' if severity == 'blocking' else 'badging'} threshold.",
        period_key=period_key, object_type="account", value_inr=unmapped,
        suggested_action="Review the mapping queue, sorted by rupee value.",
    )]


def check_opening_balances_present(conn, schema: str, tenant_id: str, entity_id: int,
                                      earliest_period_key: str) -> list[ExceptionCandidate]:
    """corpus/09 section 2.1: 'Opening balances missing for the earliest
    period' -- BLOCKING, balance sheet cannot be assembled."""
    with conn.cursor() as cur:
        cur.execute(
            f'SELECT count(*) FROM "{schema}".fact_gl_entry '
            f'WHERE tenant_id = %s AND entity_id = %s AND period_key = %s '
            f'AND is_current AND is_opening_balance',
            (tenant_id, entity_id, earliest_period_key),
        )
        count = cur.fetchone()[0]
    if count > 0:
        return []
    return [ExceptionCandidate(
        "completeness", "blocking",
        f"No opening balance rows found for {earliest_period_key}, the earliest period -- the balance "
        f"sheet cannot be assembled.",
        period_key=earliest_period_key, object_type="period", object_ref=earliest_period_key,
    )]


# ----------------------------------------------------------------- Uniqueness

def check_duplicate_file_upload(conn, schema: str, tenant_id: str) -> list[ExceptionCandidate]:
    """corpus/09 section 2.3: 'The same file uploaded twice' -- INFORMATIONAL,
    content hash catches it. Idempotent by design (src/ingest/canonical.py),
    this just surfaces that it happened."""
    with conn.cursor() as cur:
        cur.execute(
            f'SELECT content_hash, count(*) FROM "{schema}".source_file '
            f'WHERE tenant_id = %s GROUP BY content_hash HAVING count(*) > 1',
            (tenant_id,),
        )
        rows = cur.fetchall()
    return [
        ExceptionCandidate("uniqueness", "informational",
                              f"The same file content was uploaded {n} times (content hash {h.hex()[:12]}).",
                              object_type="source_file")
        for h, n in rows
    ]


def check_duplicate_content_different_voucher(conn, schema: str, tenant_id: str, entity_id: int,
                                                  period_key: str) -> list[ExceptionCandidate]:
    """corpus/11 section 2.2 defect #2: 'Duplicate voucher run, same
    content, different ids' -- a re-export under a new voucher_no, so
    row_hash-based dedup (which is keyed on voucher_no/line_no) does not
    catch it. BLOCKING per corpus/09 section 2.3's uniqueness row for
    duplicate voucher/line within a period, extended to content rather than
    id since that's what this defect actually is."""
    with conn.cursor() as cur:
        cur.execute(
            # Canonical column names per corpus/04 section 3.3: staging's
            # `voucher_date` lands as `event_date`, and there is no debit/credit
            # pair -- `amount_base` is the single signed amount (Dr positive,
            # Cr negative). "Same account, date, amount and narration" is the
            # defect this check is defined against (corpus/11 section 2.2 #2).
            f'SELECT fg.account_key, fg.event_date, fg.amount_base, fg.narration, '
            f'       count(DISTINCT fg.voucher_no), array_agg(DISTINCT fg.voucher_no), sum(fg.amount_base) '
            f'FROM "{schema}".fact_gl_entry fg '
            f'WHERE fg.tenant_id = %s AND fg.entity_id = %s AND fg.period_key = %s AND fg.is_current '
            f'GROUP BY fg.account_key, fg.event_date, fg.amount_base, fg.narration '
            f'HAVING count(DISTINCT fg.voucher_no) > 1',
            (tenant_id, entity_id, period_key),
        )
        rows = cur.fetchall()
    return [
        ExceptionCandidate(
            "uniqueness", "blocking",
            f"Identical GL content (same account, date, amount and narration) posted under {n} different "
            f"voucher numbers {vouchers}: likely the same entry re-exported rather than {n} real transactions.",
            period_key=period_key, object_type="account", object_ref=str(account_key), value_inr=abs(amt),
            suggested_action="Confirm with the source system whether these are genuinely separate vouchers.",
        )
        for account_key, _edate, _amount, _narr, n, vouchers, amt in rows
    ]


# ---------------------------------------------------------------- Consistency

def cash_flow_ties_to_balance_sheet(closing_cash_from_cashflow: Decimal | None,
                                        balance_sheet_cash: Decimal | None) -> tuple[bool, str | None]:
    """Pure: corpus/09 section 2.4 / corpus/08 section 5's hard gate --
    'Cash flow closing cash does not equal balance sheet cash' -- BLOCKING,
    cash flow not displayed. Returns (may_display, reason_if_not). Cash flow
    statement assembly is not built this sprint (not in corpus/12 sprint 2
    or 3's scope), so this is the guard function on its own, unit-tested
    against synthetic values -- it is what src/reports/ wires in once a
    cash flow assembler exists."""
    if closing_cash_from_cashflow is None or balance_sheet_cash is None:
        return False, "one or both figures are unavailable"
    if closing_cash_from_cashflow != balance_sheet_cash:
        return False, (f"cash flow closing cash ({closing_cash_from_cashflow}) does not equal balance sheet "
                         f"cash ({balance_sheet_cash})")
    return True, None


# ----------------------------------------------------------------- Continuity

def check_new_ledger_mid_year(conn, schema: str, tenant_id: str, entity_id: int,
                                 period_key: str) -> list[ExceptionCandidate]:
    """corpus/11 section 2.2 defect #5 / corpus/09 section 2.6 (continuity,
    via corpus/06 section 4.4's 'new ledger appears mid-year' handling):
    an account whose first-ever GL activity is in this period, carrying
    material value. WARNING, queued by rupee value."""
    with conn.cursor() as cur:
        cur.execute(
            f'SELECT da.account_key, da.source_account_name, SUM(ABS(fg.amount_base)) '
            f'FROM "{schema}".fact_gl_entry fg '
            f'JOIN "{schema}".dim_account da ON da.account_key = fg.account_key '
            f'WHERE fg.tenant_id = %s AND fg.entity_id = %s AND fg.is_current '
            f'AND fg.period_key = %s '
            f'AND NOT EXISTS (SELECT 1 FROM "{schema}".fact_gl_entry fg2 '
            f'                 WHERE fg2.account_key = fg.account_key AND fg2.is_current '
            f'                 AND fg2.period_key < %s) '
            f'GROUP BY da.account_key, da.source_account_name',
            (tenant_id, entity_id, period_key, period_key),
        )
        rows = cur.fetchall()
    return [
        ExceptionCandidate(
            "continuity", "warning",
            f"{name!r} has no GL activity before {period_key} -- its first appearance carries Rs {value:,.0f}.",
            period_key=period_key, object_type="account", object_ref=str(key), value_inr=value,
            suggested_action="Confirm this is a genuine new ledger, not a renamed or split existing one.",
        )
        for key, name, value in rows
    ]


def check_backdated_entries(conn, schema: str, tenant_id: str, entity_id: int,
                               as_of: date | None = None) -> list[ExceptionCandidate]:
    """corpus/09 section 2.6: 'Backdated entry found touching a locked
    period' -- INFORMATIONAL, escalating to a restatement event per section
    5. Reuses src/ingest/repull.py's trailing-90-day detection (Sprint 1)
    rather than re-implementing it; this just wraps that result as
    exception candidates and leaves the restatement decision itself to
    src/quality/period_state.restate_period."""
    from src.ingest.repull import query_backdated_entries
    as_of = as_of or date.today()
    rows = query_backdated_entries(conn, schema, tenant_id, as_of=as_of)
    return [
        ExceptionCandidate(
            "continuity", "informational",
            f"Voucher {r.voucher_no} entered {r.entry_date} for an event dated {r.event_date} "
            f"({r.days_late} days late) -- backdated.",
            period_key=f"{r.event_date.year:04d}-{r.event_date.month:02d}",
            object_type="account", object_ref=r.voucher_no,
            suggested_action="If this period is locked, this is a restatement, not a silent edit.",
        )
        for r in rows
    ]


# ---------------------------------------------------------- Sprint 6, D-041

def check_mixed_uom(conn, schema: str, tenant_id: str, entity_id: int,
                       period_key: str) -> list[ExceptionCandidate]:
    """D-041 (corpus/00, P0-BLOCKING): 'a single declared unit per product
    family... nothing per-unit computes without it.' corpus/04 section 3.6:
    'a second unit arriving for the same product raises an exception rather
    than being converted.' dim_product.declared_uom is stamped from the
    first uom ever seen for a product (src/ingest/canonical.stamp_declared_uom)
    and never changed -- this check flags every fact_production_output row
    in the period whose uom disagrees with that fixed reference point.
    BLOCKING: src/reports/manufacturing_operating.py refuses to compute any
    per-unit metric for a product with an open exception here, rather than
    averaging across incompatible units."""
    with conn.cursor() as cur:
        cur.execute(
            f'SELECT fp.product_key, dp.source_item_name, dp.declared_uom, fp.uom, SUM(fp.qty_produced) '
            f'FROM "{schema}".fact_production_output fp '
            f'JOIN "{schema}".dim_product dp ON dp.product_key = fp.product_key AND dp.is_current '
            f'WHERE fp.tenant_id = %s AND fp.entity_id = %s AND fp.is_current AND fp.period_key = %s '
            f'AND dp.declared_uom IS NOT NULL AND fp.uom <> dp.declared_uom '
            f'GROUP BY fp.product_key, dp.source_item_name, dp.declared_uom, fp.uom',
            (tenant_id, entity_id, period_key),
        )
        rows = cur.fetchall()
    return [
        ExceptionCandidate(
            "validity", "blocking",
            f"{name!r} recorded in {uom!r} this period, but its declared unit is {declared!r} -- "
            f"D-041: SPEQULA has no authority to convert between units, so per-unit metrics for this "
            f"product refuse to compute for {period_key} rather than averaging across incompatible units.",
            period_key=period_key, object_type="product", object_ref=str(product_key), value_inr=None,
            suggested_action="Confirm which unit is correct for this product family and correct the source file.",
        )
        for product_key, name, declared, uom, _qty in rows
    ]


# -------------------------------------------------------------------- Anomaly

def check_margin_sign_flip(conn, schema: str, tenant_id: str, entity_id: int,
                              period_key: str, prior_period_key: str) -> list[ExceptionCandidate]:
    """corpus/09 section 2.7: 'Margin sign flip on a product or channel' --
    WARNING, queued. Deliberately a SIGN check, not a magnitude threshold: a
    channel running entirely on the marketplace revenue model has zero COGS
    by definition (D-061) and therefore 100 percent gross margin, which is
    unusual in size but never a sign flip (there is no cost for it to have
    exceeded). corpus/03 section 7.2's own words: 'Gross margin of 100
    percent is correct there and is not a data error. The anomaly check
    must not flag it' -- satisfied here structurally, by checking sign
    change rather than distance from a typical value, not by a special case
    that excludes 100 percent."""
    with conn.cursor() as cur:
        cur.execute(
            f'SELECT channel_key, '
            f'       SUM(CASE WHEN revenue_model = %s THEN net_amount ELSE commission_earned + advertising_earned + platform_fee_earned END) '
            f'         - SUM(CASE WHEN revenue_model = %s THEN commission_amount + payment_fee ELSE 0 END) '
            f'FROM "{schema}".fact_channel_order_line '
            f'WHERE tenant_id = %s AND entity_id = %s AND is_current AND period_key = %s '
            f'GROUP BY channel_key',
            ("buyout", "buyout", tenant_id, entity_id, period_key),
        )
        current = {ck: margin for ck, margin in cur.fetchall()}
        cur.execute(
            f'SELECT channel_key, '
            f'       SUM(CASE WHEN revenue_model = %s THEN net_amount ELSE commission_earned + advertising_earned + platform_fee_earned END) '
            f'         - SUM(CASE WHEN revenue_model = %s THEN commission_amount + payment_fee ELSE 0 END) '
            f'FROM "{schema}".fact_channel_order_line '
            f'WHERE tenant_id = %s AND entity_id = %s AND is_current AND period_key = %s '
            f'GROUP BY channel_key',
            ("buyout", "buyout", tenant_id, entity_id, prior_period_key),
        )
        prior = {ck: margin for ck, margin in cur.fetchall()}

    candidates = []
    for channel_key, cur_margin in current.items():
        prior_margin = prior.get(channel_key)
        if prior_margin is None or cur_margin is None:
            continue
        if (cur_margin > 0) != (prior_margin > 0) and cur_margin != 0 and prior_margin != 0:
            candidates.append(ExceptionCandidate(
                "anomaly", "warning",
                f"Channel {channel_key} margin flipped sign between {prior_period_key} ({prior_margin}) "
                f"and {period_key} ({cur_margin}).",
                period_key=period_key, object_type="channel", object_ref=str(channel_key),
                value_inr=abs(cur_margin),
                suggested_action="Confirm this is a real margin reversal, not a misclassified cost or return.",
            ))
    return candidates


# ---------------------------------------------------------------- Freshness

@dataclass
class FreshnessStatus:
    source_system: str
    last_successful_load_at: datetime | None
    hours_since: float | None


def fetch_freshness(conn, tenant_id: str, entity_id: int) -> list[FreshnessStatus]:
    """corpus/09 section 2.8: 'Hours since last successful load, per
    source' -- displayed always, no threshold needed. The second row
    ('source stale beyond its declared SLA' -> WARNING) needs a per-source
    SLA value the corpus never states; that half is deliberately not
    evaluated here rather than guessed, the same posture as D-052."""
    with conn.cursor() as cur:
        cur.execute(
            "SELECT source_system, MAX(completed_at) FROM app.load_run "
            "WHERE tenant_id = %s AND entity_id = %s AND status = 'succeeded' "
            "GROUP BY source_system",
            (tenant_id, entity_id),
        )
        rows = cur.fetchall()
    now = datetime.now(timezone.utc)
    return [
        FreshnessStatus(source_system=src, last_successful_load_at=last_at,
                           hours_since=(now - last_at).total_seconds() / 3600 if last_at else None)
        for src, last_at in rows
    ]
